services:
  - type: web
    name: frontend
    env: node
    buildCommand: "npm run build"
    startCommand: "npm run start"
    repo: https://github.com/Vikash-shakya495/grow-together-web
    branch: main
    healthCheckPath: /health
    buildDir: /frontend
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    repo: https://github.com/Vikash-shakya495/grow-together-web
    branch: main
    healthCheckPath: /health
    buildDir: /backend
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
